import Link from 'next/link';
import type { Metadata } from 'next'
import './globals.css'
import { useEffect, useState } from "react"; //전역 스타일

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by Beauty',
}

interface Topic {
    id: string;
    title: string;
    body: {content : string};
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const resp = await fetch('http://localhost:9999/topics');
    const topics = await resp.json();
  return (
    <html>
      <body>
      <h1><Link href="/">WEB</Link></h1>

      <ol>
          {topics.map((topic)=>{
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.body.content }</Link></li>
          })}
      </ol>
      {children}

      <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="delete"/></li>
      </ul>
      </body>
    </html>
  )
}
