import Link from 'next/link';
import type { Metadata } from 'next'
import './globals.css'
import Control from './Control'
import {func} from "prop-types";

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by Beauty',
}

interface Topic {
    id: string;
    title: string;
    body: {content : string};
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', { cache: 'no-store' }); //fetch하여 생긴 cache 지우는 매커니즘: Revalidation Data
    const topics: Topic[] = await resp.json();
  return (
    <html>
      <body>
      <h1><Link href="/">WEB</Link></h1>

      <ol>
          {topics.map((topic)=>{
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.body.content }</Link></li>
          })}
      </ol>
      {children}

      <Control />
      </body>
    </html>
  )
}
