'use client'; //useEffect, useState 는 클라이언트 컴포넌트임
import Link from 'next/link';
import type { Metadata } from 'next'
import './globals.css'
import { useEffect, useState } from "react"; //전역 스타일

//metadata는 서버 컴포넌트이므로 주석처리
// export const metadata: Metadata = {
//   title: 'Web tutorials',
//   description: 'Generated by Beauty',
// }

interface Topic {
    id: string;
    title: string;
    body: {content : string};
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const [topics, setTopics] = useState<Topic[]>([]);
    useEffect(()=>{
        fetch('http://localhost:9999/topics')
            .then(resp=> {
                console.log(resp)
                return resp.json()
            })
            .then(result=>{
                console.log(result)
                return setTopics(result)
            });
    }, []);
  return (
    <html>
      <body>
      <h1><Link href="/">WEB</Link></h1>

      <ol>
          {/*<li><Link href="/read/1">html</Link></li>*/}
          {/*<li><Link href="/read/2">css</Link></li>*/}
          {topics.map((topic)=>{
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.body.content }</Link></li>
          })}
      </ol>
      {children}

      <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="delete"/></li>
      </ul>
      </body>
    </html>
  )
}
